### ISSUE TITLE
libevent-dev needed

### ISSUE THREAD

**Issue by derekgtaylor** [ejwessel/raspnode_config#2]
https://github.com/ejwessel/raspnode_config/blob/2501ca2570ef91481595286ec62ae77392dc4d1c/roles/litecoin/tasks/main.yml#L10

**Comment by ejwessel** [comment]
this is probably the case for bitcoin too. I will add to both bitcoin and litecoin

**Comment by ejwessel** [comment]
https://github.com/ejwessel/raspnode_config/issues/2

**Comment by ejwessel** [comment]
https://github.com/ejwessel/raspnode_config/pull/4

**Comment by ejwessel** [comment]
turns out it was already added to the bitcoin role
