### ISSUE TITLE
Add network ping test

### ISSUE THREAD

**Issue by derekgtaylor** [ejwessel/raspnode_config#20]
https://mmonit.com/monit/documentation/monit.html#NETWORK-PING-TEST

**Comment by derekgtaylor** [comment]
might make more sense for me to setup smtp before I do this.

**Comment by ejwessel** [comment]
This may not be all that useful if there is no internet. If there is no network then there won't be the ability to send alerts.

**Comment by ejwessel** [comment]
Closing because if no network then no alert will be sent.
